export const PROJECT_TYPES = [
  { value: 'professional', label: 'Professional Work' },
  { value: 'creative', label: 'Creative Experiments' },
  { value: 'game', label: 'Games' },
] as const

export const DEFAULT_PROJECTS = [
  {
    id: 1,
    title: 'Minimalist E-commerce',
    slug: 'minimalist-ecommerce',
    description: 'A clean, elegant online store built with a focus on simplicity and user experience.',
    content: 'This minimalist e-commerce platform focuses on delivering a clean, intuitive shopping experience with careful attention to typography and whitespace.',
    image: '/images/projects/minimalist-ecommerce.jpg',
    tags: ['React', 'NextJS', 'Monochrome Design'],
    type: 'professional' as const,
  },
  {
    id: 2,
    title: 'AI Content Studio',
    slug: 'ai-content-studio',
    description: 'An AI-powered application that generates content with a sleek, modern interface.',
    content: 'The AI Content Studio combines cutting-edge artificial intelligence with a clean, monochromatic user interface.',
    image: '/images/projects/ai-content-studio.jpg',
    tags: ['React', 'AI', 'Black & White'],
    type: 'creative' as const,
  },
  {
    id: 3,
    title: 'Brutalist Portfolio',
    slug: 'brutalist-portfolio',
    description: 'A stark, high-contrast portfolio site with bold typography and minimal color.',
    content: 'This portfolio embraces brutalist web design principles with raw HTML/CSS implementations.',
    image: '/images/projects/brutalist-portfolio.jpg',
    tags: ['HTML', 'CSS', 'Brutalism'],
    type: 'creative' as const,
  },
  {
    id: 4,
    title: 'Monochrome Dashboard',
    slug: 'monochrome-dashboard',
    description: 'A sophisticated admin dashboard with a black and white color scheme and clean typography.',
    content: 'The Monochrome Dashboard provides data visualization and system management tools in an elegant black and white interface.',
    image: '/images/projects/monochrome-dashboard.jpg',
    tags: ['React', 'Monochrome', 'Dashboard'],
    type: 'professional' as const,
  },
  {
    id: 5,
    title: 'Physics Puzzle Game',
    slug: 'physics-puzzle-game',
    description: 'A browser-based physics puzzle game with 3D graphics and realistic simulation.',
    content: 'A challenging puzzle game that uses physics simulation for realistic object interactions.',
    image: '/images/projects/physics-puzzle-game.jpg',
    tags: ['Three.js', 'Physics', 'Games'],
    type: 'game' as const,
  },
  {
    id: 6,
    title: 'Architect Showcase',
    slug: 'architect-showcase',
    description: 'A portfolio site for an architecture firm with elegant, spacious layouts.',
    content: 'The Architect Showcase features interactive 3D models and immersive photography of architectural projects.',
    image: '/images/projects/architect-showcase.jpg',
    tags: ['Three.js', 'Architecture', 'Minimalism'],
    type: 'creative' as const,
  },
]